SCREEN_WIDTH=400
SCREEN_HEIGHT=600

ALIEN_1_WIDTH = 32
ALIEN_1_HEIGHT = 16
ALIEN_2_WIDTH = 32
ALIEN_2_HEIGHT = 16
GUN_WIDTH = 32
GUN_HEIGHT = 32
SAUCER_HEIGHTH = 16
SAUCER_WIDTH = 16
ALIEN_MOVE_LIMIT = 30
ALIEN_MOVE_DISTANCE = 5


GUN_LEFT_LIMIT = - (SCREEN_WIDTH / 2) + 30
GUN_RIGHT_LIMIT = (SCREEN_WIDTH / 2) - 30
GUN_VER_LIMIT = -2 + 20
GUN_MOVE_DISTANCE = 20
GUN_COLLISION_DISTANCE = 20
GUN_INITIAL_POSITION = (0, -250)

BULLET_BOTTOM_LIMIT = - (SCREEN_HEIGHT / 2) + 30
BULLET_TOP_LIMIT = (SCREEN_HEIGHT / 2) - 30
BULLET_MOVE_DISTANCE = 20
BULLET_COLLISION_DISTANCE = 30
BULLET_MOVE_SPEED = 100 # mseconds

ALIEN_FIRE_TICK = 20    # fire every 20 ticks

BUTTON_START_POS = (GUN_LEFT_LIMIT - 10, GUN_VER_LIMIT - 10)
BUTTON_FONT_SIZE = 12
BUTTON_FONT = ('Arial', BUTTON_FONT_SIZE, 'bold')

TILE_ROWS = 4
TILE_COLUMNS = 8    
TILE_SEP_X = 45
TILE_SEP_Y = 30
TILE_PADX = 60
TILE_PADY = 30
TILE_LEFT_LIMIT = - (SCREEN_WIDTH / 2) + TILE_PADX
TILE_RIGHT_LIMIT = (SCREEN_WIDTH / 2) - TILE_PADX
TILE_TOP_LIMIT = (SCREEN_HEIGHT / 2) - TILE_PADY
TILE_BOTTOM_LIMIT = - (SCREEN_HEIGHT / 2) + TILE_PADY


def print_config():
    print(f"SCREEN_WIDTH: {SCREEN_WIDTH}")
    print(f"SCREEN_HEIGHT: {SCREEN_HEIGHT}")
    print("------------------------")
    print(f"GUN_LEFT_LIMIT: {GUN_LEFT_LIMIT}")
    print(f"GUN_RIGHT_LIMIT: {GUN_RIGHT_LIMIT}")
    print(f"GUN_MOVE_DISTANCE: {GUN_MOVE_DISTANCE}")
    print(f"GUN_COLLISION_DISTANCE: {GUN_COLLISION_DISTANCE}")
    print("------------------------")
    print(f"BULLET_MOVE_DISTANCE: {BULLET_MOVE_DISTANCE}")
    print(f"BULLET_MOVE_SPEED: {BULLET_MOVE_SPEED}")
    print(f"BULLET_COLLISION_DISTANCE: {BULLET_COLLISION_DISTANCE}")    
    print("------------------------")
    print(f"ALIEN TILE_ROWS: {TILE_ROWS}")
    print(f"ALIEN TILE_COLUMNS: {TILE_COLUMNS}")  
    print(f"ALIEN TILE_LEFT_LIMIT: {TILE_LEFT_LIMIT}")
    print(f"ALIEN TILE_TOP_LIMIT: {TILE_TOP_LIMIT}")
    print(f"TILE_RIGHT_LIMIT: {TILE_RIGHT_LIMIT}")
    print(f"TILE_BOTTOM_LIMIT: {TILE_BOTTOM_LIMIT}")
